import Link from 'next/link'
import { redirect, notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

const titles:Record<string,string>={campaigns:'My Campaigns',earnings:'Earnings & Wallet',referrals:'Referrals',profile:'Profile',settings:'Settings'}
export default async function Section({params}:{params:{section:string}}){const title=titles[params.section];if(!title)notFound();const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:p}=await supabase.from('users').select('name,email,balance,total_earned,referral_code,referred_by,youtube_channel_id,youtube_channel_title,youtube_subscriber_count,is_paid,strikes').eq('id',user.id).single();if(!p)redirect('/register');
 if(params.section==='profile')return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-4xl"><h1 className="text-4xl font-black">Profile</h1><div className="glass mt-7 rounded-2xl p-7"><p className="text-2xl font-black">{p.name||'VSBIL member'}</p><p className="mt-1 text-slate-500">{p.email}</p><div className="mt-7 grid gap-4 md:grid-cols-2"><Info label="YouTube" value={p.youtube_channel_title||'Not connected'}/><Info label="Subscribers" value={Number(p.youtube_subscriber_count).toLocaleString()}/><Info label="Account" value={p.is_paid?'Active':'Awaiting activation'}/><Info label="Trust strikes" value={`${p.strikes}/3`}/></div><Link href="/api/youtube/connect" className="mt-7 inline-block rounded-xl bg-red-600 px-5 py-3 font-bold text-white">{p.youtube_channel_id?'Reconnect YouTube':'Connect YouTube'}</Link></div></div></main>
 if(params.section==='settings')return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-4xl"><h1 className="text-4xl font-black">Settings</h1><div className="mt-7 space-y-4"><div className="glass rounded-2xl p-6"><h2 className="font-black">Account security</h2><p className="mt-2 text-slate-500">Use a strong password and keep your Google/YouTube account secure.</p></div><div className="glass rounded-2xl p-6"><h2 className="font-black">Privacy & data</h2><p className="mt-2 text-slate-500">Request export, deletion or YouTube access revocation.</p><Link href="/data-rights" className="mt-4 inline-block font-bold text-red-600">Manage data rights →</Link></div></div></div></main>
 if(params.section==='referrals'){const {count}=await supabase.from('referrals').select('*',{count:'exact',head:true}).eq('referrer_id',user.id);const {data:rows}=await supabase.from('referrals').select('commission_earned,created_at').eq('referrer_id',user.id).order('created_at',{ascending:false}).limit(20);const earned=(rows||[]).reduce((a,r)=>a+Number(r.commission_earned),0);return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-4xl"><h1 className="text-4xl font-black">Referrals</h1><div className="glass mt-7 rounded-2xl p-7"><p className="text-sm text-slate-500">Your referral code</p><p className="mt-2 text-3xl font-black tracking-widest">{p.referral_code}</p><p className="mt-4 text-slate-500">Share: {process.env.NEXT_PUBLIC_APP_URL}/register?ref={p.referral_code}</p></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Info label="People referred" value={String(count||0)}/><Info label="Referral earnings" value={`GHS ${earned.toFixed(2)}`}/></div></div></main>}
 if(params.section==='campaigns'){const {data}=await supabase.from('campaigns').select('id,youtube_video_title,status,quantity,completed_count,total_budget,platform_fee,created_at').eq('user_id',user.id).order('created_at',{ascending:false});return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><h1 className="text-4xl font-black">My Campaigns</h1><Link href="/campaigns/new" className="rounded-xl bg-red-600 px-5 py-3 font-bold text-white">New campaign</Link></div><div className="mt-7 space-y-4">{data?.map(c=><div key={c.id} className="glass rounded-2xl p-6"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><h2 className="font-black">{c.youtube_video_title}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold dark:bg-slate-800">{c.status}</span></div><p className="mt-2 text-sm text-slate-500">{c.completed_count}/{c.quantity} completed · Budget ${Number(c.total_budget).toFixed(2)}</p></div>)}{!data?.length&&<div className="rounded-2xl border border-dashed p-12 text-center text-slate-500">No campaigns yet. Create your first campaign.</div>}</div></div></main>}
 const {data:tx}=await supabase.from('transactions').select('type,amount,currency,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50);return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-5xl"><h1 className="text-4xl font-black">{title}</h1><div className="mt-7 grid gap-5 md:grid-cols-2"><Info label="Available balance" value={`GHS ${Number(p.balance).toFixed(2)}`}/><Info label="Lifetime earned" value={`GHS ${Number(p.total_earned).toFixed(2)}`}/></div><div className="glass mt-7 overflow-hidden rounded-2xl"><div className="border-b p-5 font-black">Recent transactions</div>{tx?.map((t,i)=><div key={i} className="flex justify-between border-b p-5 last:border-0"><span className="capitalize">{t.type.replaceAll('_',' ')}</span><span className="font-bold">GHS {Number(t.amount).toFixed(2)}</span></div>)}</div></div></main>}
function Info({label,value}:{label:string,value:string}){return <div className="rounded-xl border p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-black">{value}</p></div>}
