'use client'
import {useEffect,useState} from 'react'

type Campaign={id:string;user_id:string;youtube_video_title:string|null;quantity:number;completed_count:number;total_charge_minor:number;status:string;policy_review_status:string;promotion_mode:string;created_at:string}
const actions=['policy_approve','policy_reject','approve','reject','pause','resume','cancel'] as const
export default function AdminCampaigns(){
 const [rows,setRows]=useState<Campaign[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState('')
 async function load(){const r=await fetch('/api/admin/campaigns');const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load campaigns');setRows(d.campaigns||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 async function act(id:string,action:string){const needsReason=action==='policy_reject'||action==='reject'||action==='pause'||action==='cancel';const reason=needsReason?(window.prompt(`Reason for ${action.replaceAll('_',' ')}:`)||''):'';if(needsReason&&!reason)return;setBusy(`${id}:${action}`);setError('');try{const r=await fetch(`/api/admin/campaigns/${id}/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed');await load()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}}
 const visible=(c:Campaign,a:string)=>a==='policy_approve'||a==='policy_reject'?c.policy_review_status==='pending':a==='approve'?c.status==='pending_approval':a==='pause'?['approved','active'].includes(c.status):a==='resume'?c.status==='paused':a==='reject'?['pending_approval','approved','active','paused'].includes(c.status):a==='cancel'?['pending_approval','approved','active','paused'].includes(c.status):false
 return <main className="min-h-screen bg-slate-50 px-5 py-10 dark:bg-slate-950"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-widest text-red-600">VSBILL Admin</p><h1 className="mt-2 text-4xl font-black">Campaign review</h1><p className="mt-2 text-slate-500">Review policy first, then approve or reject the lifecycle transition.</p>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-8 overflow-x-auto rounded-2xl border bg-white dark:bg-slate-900"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Campaign</th><th className="p-4">Mode</th><th className="p-4">Progress</th><th className="p-4">Policy</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-b last:border-0"><td className="p-4"><b>{c.youtube_video_title||'Untitled'}</b><div className="text-xs text-slate-400">{c.user_id}</div></td><td className="p-4">{c.promotion_mode}</td><td className="p-4">{c.completed_count}/{c.quantity}</td><td className="p-4">{c.policy_review_status}</td><td className="p-4">{c.status}</td><td className="p-4"><div className="flex flex-wrap gap-2">{actions.filter(a=>visible(c,a)).map(a=><button key={a} disabled={!!busy} onClick={()=>act(c.id,a)} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-50">{busy===`${c.id}:${a}`?'…':a.replaceAll('_',' ')}</button>)}</div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-slate-500">No campaigns awaiting review.</p>}</div></div></main>
}
