services:
  - type: web
    name: vsbil-tube-boost-test
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
