import Link from 'next/link'
import { notFound } from 'next/navigation'

const pages: Record<string,{title:string;intro:string;sections:string[]}>= {
  about:{title:'About VSBILL',intro:'A Ghana-ready creator growth platform built around transparent pricing, accountable verification and protected payments.',sections:['VSBILL provides a structured home for creator promotion, advertiser campaigns and verified participation.','Financial actions are server controlled and sensitive actions are designed to be auditable.']},
  'how-it-works':{title:'How it works',intro:'Two paths: promote a creator campaign or complete eligible Discovery & Engagement Tasks.',sections:['Advertisers validate a YouTube video, choose eligible engagement requirements, set quantity and budget, then submit the campaign for approval.','Earners verify email, connect YouTube, activate the account and complete assigned tasks through the verification flow before earnings are credited.','Google verification statement: We help creators grow via TrueView ad promotion and organic engagement tasks. No incentivized exchange.']},
  pricing:{title:'Pricing',intro:'Platform activation is GHS 160 after required verification.',sections:['Entry allocation is 20% referral commission, 10% user cashback and 70% platform allocation.','Campaign owners pay their campaign budget plus the configured platform fee. Payments are verified server-side.']},
  guidelines:{title:'Community guidelines',intro:'Quality, honesty and account safety are mandatory.',sections:['Do not unsubscribe after completing a subscription task. Do not use bots, fake accounts, automation, account farms or scripted playback.','Keep required playback in the foreground and complete verification prompts honestly. Violations can revoke earnings or restrict an account.']},
  terms:{title:'Terms of Service',intro:'These terms govern access to VSBILL.',sections:['Users must provide accurate account information and comply with applicable platform, payment and creator-network rules.','We may suspend or terminate accounts involved in fraud, payment abuse, manipulation or repeated task reversals.']},
  privacy:{title:'Privacy Policy',intro:'VSBILL collects data needed to operate, secure and improve the service.',sections:['Data can include account details, device/security signals, payment references and authorized YouTube channel information. Payment credentials remain with the payment provider.','We apply access controls and provide export, deletion and connected-account revocation workflows subject to legal requirements.']},
  'data-rights':{title:'Your data rights',intro:'Manage your personal data through the account security workflow.',sections:['You can request an export, account deletion or revocation of connected YouTube access.','Privacy questions can be submitted through VSBILL support.']},
  contact:{title:'Contact support',intro:'Need help with payments, campaigns, shops or verification?',sections:['Use the support form in your authenticated dashboard for account-specific issues. Include the relevant transaction or campaign reference when available.']},
  'verify-email':{title:'Verify your email',intro:'Check your inbox for the Supabase verification email.',sections:['Email verification is required before activation and payment. If the message did not arrive, request another verification email from the authentication screen.']},
}
export default function PublicPage({params}:{params:{slug:string}}){const p=pages[params.slug];if(!p)notFound();return <main className="min-h-screen"><nav className="mx-auto flex max-w-5xl justify-between px-6 py-6"><Link href="/" className="font-black">VSBILL</Link><Link href="/register" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white dark:bg-white dark:text-slate-950">Get started</Link></nav><article className="mx-auto max-w-4xl px-6 py-16"><p className="text-sm font-bold uppercase tracking-widest text-red-600">VSBILL</p><h1 className="mt-3 text-5xl font-black tracking-tight">{p.title}</h1><p className="mt-6 text-xl leading-8 text-slate-600 dark:text-slate-300">{p.intro}</p><div className="mt-12 space-y-5">{p.sections.map((s,i)=><section key={i} className="glass rounded-2xl p-7 text-lg leading-8 shadow-premium"><p>{s}</p></section>)}</div></article></main>}
