import Link from 'next/link'
import { notFound } from 'next/navigation'

const pages: Record<string,{title:string;intro:string;sections:string[]}>={
 about:{title:'About VSBIL TUBE BOOST',intro:'A Ghana-ready YouTube campaign marketplace built around transparent pricing, verified participation and safer creator growth.',sections:['Our mission is to give advertisers a structured way to reach real audiences while giving participants a clear, rules-based earning experience.','We design every financial action to be server controlled and every sensitive account action to be auditable.']},
 'how-it-works':{title:'How it works',intro:'Two simple paths: run a campaign or complete verified tasks.',sections:['Advertisers submit a YouTube video, choose eligible tasks, set quantity and budget, then wait for approval before launch.','Earners connect their YouTube account, activate their account, complete assigned tasks in the embedded player and pass verification before earnings are credited.']},
 pricing:{title:'Pricing',intro:'A clear $10-equivalent GHS entry fee unlocks the platform after verification.',sections:['The entry fee is split according to the platform settings: 20% referral commission, 10% new-user cashback and 70% platform allocation.','Campaign owners pay their campaign budget plus the configured platform commission. All payments are recorded and verified server-side.']},
 guidelines:{title:'Community guidelines',intro:'Quality and honesty are mandatory.',sections:['Do not unsubscribe after completing a subscription task. Do not use bots, fake accounts, automation, VPN-based account farms or scripted playback.','Watch the required portion in the embedded player, keep the page visible when required and complete verification prompts honestly. Violations can revoke earnings or restrict the account.']},
 terms:{title:'Terms of Service',intro:'These terms govern access to VSBIL TUBE BOOST.',sections:['Users must provide accurate account information, maintain control of their connected YouTube account and comply with YouTube and Paystack rules.','We may suspend or terminate accounts involved in fraud, payment abuse, manipulation or repeated task reversals.']},
 privacy:{title:'Privacy Policy',intro:'We collect only data needed to operate, secure and improve the service.',sections:['Data may include account details, device/security signals, payment references and authorized YouTube channel information. Payment credentials are handled by the payment provider.','We apply access controls and security measures and provide data-access, export, deletion and YouTube-revocation workflows subject to legal and operational requirements.']},
 'data-rights':{title:'Your data rights',intro:'Control your account data from one place.',sections:['You can request an export, request account deletion or request revocation of connected YouTube access. Requests are recorded and processed through the account security workflow.','For privacy questions, contact support with the email associated with your account.']},
 contact:{title:'Contact support',intro:'Need help with payments, campaigns or task verification?',sections:['Use the support form in your authenticated dashboard for account-specific issues. Include the relevant transaction reference or campaign ID when available.']},
 'verify-email':{title:'Verify your email',intro:'Check your inbox for the Supabase verification email, then return here to continue activation.',sections:['Email verification is required before the entry payment and earning workflow can be completed. If you did not receive an email, request another verification message from the authentication screen.']},
}
export default function PublicPage({params}:{params:{slug:string}}){const p=pages[params.slug];if(!p)notFound();return <main className="min-h-screen"><nav className="mx-auto flex max-w-5xl justify-between px-6 py-6"><Link href="/" className="font-black">VSBIL <span className="gradient-text">TUBE BOOST</span></Link><Link href="/register" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white dark:bg-white dark:text-slate-950">Get started</Link></nav><article className="mx-auto max-w-4xl px-6 py-16"><p className="text-sm font-bold uppercase tracking-widest text-red-600">VSBIL TUBE BOOST</p><h1 className="mt-3 text-5xl font-black tracking-tight">{p.title}</h1><p className="mt-6 text-xl leading-8 text-slate-600 dark:text-slate-300">{p.intro}</p><div className="mt-12 space-y-5">{p.sections.map((s,i)=><section key={i} className="glass rounded-2xl p-7 text-lg leading-8 shadow-premium"><p>{s}</p></section>)}</div></article></main>}
