'use client'
import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

export default function RegisterPage(){
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [ref,setRef]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);const {error}=await createClient().auth.signUp({email,password,options:{data:{name,referral_code:ref||undefined},emailRedirectTo:`${location.origin}/verify-email`}});setLoading(false);if(error){setError(error.message);return}window.location.href='/verify-email'}
 return <main className="flex min-h-screen items-center justify-center px-6"><form onSubmit={submit} className="glass w-full max-w-md rounded-2xl p-8 shadow-premium"><h1 className="text-3xl font-black">Create your VSBILL account</h1><p className="mt-2 text-slate-500">Verify your email and connect YouTube before the mandatory GHS 160 activation payment.</p><label className="mt-6 block text-sm font-semibold">Full name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border bg-transparent px-4 py-3"/></label><label className="mt-4 block text-sm font-semibold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border bg-transparent px-4 py-3"/></label><label className="mt-4 block text-sm font-semibold">Password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border bg-transparent px-4 py-3"/></label><label className="mt-4 block text-sm font-semibold">Referral code <span className="font-normal text-slate-400">(optional)</span><input value={ref} onChange={e=>setRef(e.target.value.toUpperCase())} className="mt-2 w-full rounded-xl border bg-transparent px-4 py-3 uppercase"/></label>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-red-600 px-4 py-3 font-bold text-white disabled:opacity-50">{loading?'Creating…':'Create account'}</button><p className="mt-6 text-center text-sm text-slate-500">Already registered? <Link className="font-bold text-red-600" href="/login">Sign in</Link></p></form></main>
}
