'use client'
import { useMemo, useState } from 'react'

type Product={id:string;name:string;selling_price:number;description:string|null;image_url:string|null;category:string|null}
export default function ShopClient({products,deliveryFee,shopName,shopId}:{products:Product[];deliveryFee:number;shopName:string;shopId:string}){
 const [cart,setCart]=useState<Record<string,number>>({}); const [query,setQuery]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
 const visible=useMemo(()=>products.filter(p=>`${p.name} ${p.category||''}`.toLowerCase().includes(query.toLowerCase())),[products,query]); const lines=products.filter(p=>cart[p.id]).map(p=>({...p,qty:cart[p.id]})); const subtotal=lines.reduce((n,p)=>n+Number(p.selling_price)*p.qty,0); const total=subtotal+(lines.length?deliveryFee:0)
 async function checkout(){if(!lines.length)return; setBusy(true);setMessage(''); try{const r=await fetch('/api/shop/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({shopId,buyer_name:'Guest customer',buyer_phone:'',buyer_email:'',delivery_address:'',payment_method:'cod',items:lines.map(p=>({product_id:p.id,quantity:p.qty}))})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Checkout failed');setMessage(`Order ${j.order.order_number} created. Complete payment according to the selected method.`);setCart({})}catch(e){setMessage(e instanceof Error?e.message:'Checkout failed')}finally{setBusy(false)}}
 return <div className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..." className="rounded-xl border bg-white px-4 py-3 outline-none dark:bg-slate-900"/><div className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white dark:bg-white dark:text-slate-950">Cart {lines.reduce((n,p)=>n+p.qty,0)} · GHS {total.toFixed(2)}</div></div>{message&&<div className="mb-5 rounded-xl border p-4 text-sm">{message}</div>}<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{visible.map(p=><article key={p.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm dark:bg-slate-900">{p.image_url?<img src={p.image_url} alt="" className="h-48 w-full object-cover"/>:<div className="h-48 bg-slate-100 dark:bg-slate-800"/>}<div className="p-4"><p className="text-xs text-slate-500">{p.category||'Product'}</p><h2 className="mt-1 font-bold">{p.name}</h2><p className="mt-2 font-black">GHS {Number(p.selling_price).toFixed(2)}</p><button onClick={()=>setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}))} className="mt-4 w-full rounded-xl bg-red-600 px-4 py-3 font-bold text-white">Add to cart</button></div></article>)}</div>{lines.length>0&&<div className="sticky bottom-3 mt-8 rounded-2xl border bg-white/95 p-5 shadow-xl backdrop-blur dark:bg-slate-900/95"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-bold">Checkout</p><p className="text-sm text-slate-500">Subtotal GHS {subtotal.toFixed(2)} · Delivery GHS {deliveryFee.toFixed(2)} · Total GHS {total.toFixed(2)}</p></div><button disabled={busy} onClick={checkout} className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white disabled:opacity-50 dark:bg-white dark:text-slate-950">{busy?'Processing...':'Place order (COD)'}</button></div></div>}</div>
}
