'use client'
import { useEffect,useRef,useState } from 'react'
import { useParams } from 'next/navigation'
declare global { interface Window { YT:any; onYouTubeIframeAPIReady?:()=>void } }
export default function TaskPlayer(){const {id}=useParams<{id:string}>();const [task,setTask]=useState<any>(null);const [seconds,setSeconds]=useState(0);const [error,setError]=useState('');const [ready,setReady]=useState(false);const player=useRef<any>(null);const visible=useRef(true)
 useEffect(()=>{const h=()=>{visible.current=document.visibilityState==='visible'};document.addEventListener('visibilitychange',h);return()=>document.removeEventListener('visibilitychange',h)},[])
 useEffect(()=>{fetch(`/api/tasks/${id}`).then(r=>r.json()).then(d=>{if(d.error)setError(d.error);else setTask(d)}).catch(()=>setError('Unable to load task'))},[id])
 useEffect(()=>{if(!task)return;const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.async=true;window.onYouTubeIframeAPIReady=()=>{player.current=new window.YT.Player('yt-player',{videoId:task.video_id,width:'100%',height:'100%',playerVars:{playsinline:1,rel:0},events:{onStateChange:(e:any)=>{if(e.data===1)setReady(true)}}})};document.body.appendChild(script);const timer=setInterval(()=>{if(player.current&&ready&&visible.current)setSeconds(Math.floor(player.current.getCurrentTime?.()||0))},1000);return()=>{clearInterval(timer);script.remove()}},[task,ready])
 async function complete(){setError('');if(!visible.current)return setError('Keep the task visible before verification.');const duration=Number(task.duration_seconds);const percent=duration?Math.min(100,seconds/duration*100):0;if(percent<100)return setError('Watch the full required video before completing.');const r=await fetch('/api/tasks/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task_id:id,watch_seconds:seconds,watch_percent:percent,visibility_failures:0})});const d=await r.json();if(!r.ok)return setError(d.error||'Verification failed');location.href='/dashboard/earnings'}
 if(error&&!task)return <main className="p-8">{error}</main>;return <main className="min-h-screen bg-slate-950 p-5 text-white md:p-10"><div className="mx-auto max-w-5xl"><h1 className="text-2xl font-black">{task?.title||'Loading task…'}</h1><div className="mt-6 aspect-video overflow-hidden rounded-2xl bg-black"><div id="yt-player" className="h-full w-full"/></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Stat label="Player time" value={`${seconds}s / ${task?.duration_seconds||0}s`}/><Stat label="Progress" value={`${task?.duration_seconds?Math.min(100,Math.floor(seconds/task.duration_seconds*100)):0}%`}/><Stat label="Reward" value={`$${Number(task?.earning_amount||0).toFixed(2)}`}/></div>{error&&<p className="mt-5 rounded-xl bg-red-500/15 p-4 text-red-200">{error}</p>}<button disabled={!ready||seconds<Number(task?.duration_seconds||999999)} onClick={complete} className="mt-6 w-full rounded-xl bg-red-600 px-5 py-4 font-black disabled:opacity-40">Complete verification</button><p className="mt-4 text-sm text-slate-400">Keep this tab visible. Skipping or abnormal playback can trigger fraud review.</p></div></main>}
function Stat({label,value}:{label:string,value:string}){return <div className="rounded-xl bg-white/10 p-4"><p className="text-sm text-slate-400">{label}</p><p className="text-2xl font-black">{value}</p></div>}
