'use client'
import { useEffect,useRef,useState } from 'react'
import { useParams,useRouter } from 'next/navigation'
import FingerprintJS from '@fingerprintjs/fingerprintjs'
declare global { interface Window { YT:any; onYouTubeIframeAPIReady?:()=>void } }
export default function TaskPlayer(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [task,setTask]=useState<any>(null);const [session,setSession]=useState<any>(null);const [seconds,setSeconds]=useState(0);const [error,setError]=useState('');const [ready,setReady]=useState(false);const player=useRef<any>(null);const visible=useRef(true);const lastSeconds=useRef(0);const playbackSecondsRef=useRef(0);const mouseActive=useRef(false);const seekDetected=useRef(false)
 useEffect(()=>{try{const raw=sessionStorage.getItem(`vsbill-task-session:${id}`);if(raw)setSession(JSON.parse(raw))}catch{}const move=()=>{mouseActive.current=true};const h=()=>{visible.current=document.visibilityState==='visible'};document.addEventListener('visibilitychange',h);window.addEventListener('mousemove',move,{passive:true});return()=>{document.removeEventListener('visibilitychange',h);window.removeEventListener('mousemove',move)}},[id])
 useEffect(()=>{let cancelled=false;(async()=>{try{let r=await fetch(`/api/tasks/${id}`);if(r.ok){const d=await r.json();if(!cancelled)setTask(d);return}const fp=await FingerprintJS.load();const result=await fp.get();const start=await fetch('/api/tasks/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({campaign_id:id,device_fingerprint:result.visitorId})});const d=await start.json();if(!start.ok)throw new Error(d.error||'Unable to start task');if(!cancelled){sessionStorage.setItem(`vsbill-task-session:${d.task_id}`,JSON.stringify(d));setSession(d);router.replace(`/dashboard/tasks/${d.task_id}`)}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Unable to load task')}})();return()=>{cancelled=true}},[id,router])
 useEffect(()=>{if(!task)return;const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.async=true;window.onYouTubeIframeAPIReady=()=>{player.current=new window.YT.Player('yt-player',{videoId:task.video_id,width:'100%',height:'100%',playerVars:{playsinline:1,rel:0},events:{onStateChange:(e:any)=>{if(e.data===1)setReady(true)}}})};document.body.appendChild(script);const timer=setInterval(()=>{if(player.current&&ready){const now=Number(player.current.getCurrentTime?.()||0);if(now+2<lastSeconds.current)seekDetected.current=true;lastSeconds.current=now;playbackSecondsRef.current=Math.max(playbackSecondsRef.current,now);if(visible.current)setSeconds(Math.floor(now))}},1000);return()=>{clearInterval(timer);script.remove();player.current?.destroy?.()};},[task,ready])
 useEffect(()=>{if(!session?.session_id)return;const heartbeat=async()=>{try{await fetch('/api/tasks/heartbeat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:session.session_id,playback_seconds:playbackSecondsRef.current,visibility_state:document.visibilityState,playback_rate:Number(player.current?.getPlaybackRate?.()||1),seek_detected:seekDetected.current,mouse_activity:mouseActive.current})});mouseActive.current=false;seekDetected.current=false}catch{}};const timer=setInterval(heartbeat,5000);return()=>clearInterval(timer)},[session?.session_id])
 async function complete(){setError('');if(!visible.current)return setError('Keep the task visible before verification.');if(!session?.session_id)return setError('Task session is still starting.');const key=crypto.randomUUID();const r=await fetch('/api/tasks/verify',{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':key},body:JSON.stringify({task_id:task.id,session_id:session.session_id,session_nonce:session.session_nonce})});const d=await r.json();if(!r.ok)return setError(d.error||'Verification failed');sessionStorage.removeItem(`vsbill-task-session:${task.id}`);router.push('/dashboard/earnings')}
 if(error&&!task)return <main className="p-8">{error}</main>;return <main className="min-h-screen bg-slate-950 p-5 text-white md:p-10"><div className="mx-auto max-w-5xl"><h1 className="text-2xl font-black">{task?.title||'Starting task…'}</h1><div className="mt-6 aspect-video overflow-hidden rounded-2xl bg-black"><div id="yt-player" className="h-full w-full"/></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Stat label="Player time" value={`${seconds}s / ${task?.duration_seconds||0}s`}/><Stat label="Progress" value={`${task?.duration_seconds?Math.min(100,Math.floor(seconds/task.duration_seconds*100)):0}%`}/><Stat label="Reward" value={`$${Number(task?.earning_amount||0).toFixed(2)}`}/></div>{error&&<p className="mt-5 rounded-xl bg-red-500/15 p-4 text-red-200">{error}</p>}<button disabled={!ready||seconds<Number(task?.duration_seconds||999999)||!session?.session_id} onClick={complete} className="mt-6 w-full rounded-xl bg-red-600 px-5 py-4 font-black disabled:opacity-40">Complete verification</button><p className="mt-4 text-sm text-slate-400">Keep this tab visible. Server-side playback evidence is required for verification.</p></div></main>}
function Stat({label,value}:{label:string,value:string}){return <div className="rounded-xl bg-white/10 p-4"><p className="text-sm text-slate-400">{label}</p><p className="text-2xl font-black">{value}</p></div>}
