'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'

type Campaign={id:string;youtube_video_title:string|null;thumbnail:string|null;quantity:number;completed_count:number;total_budget_minor:number;total_charge_minor:number;currency:string;status:string;policy_review_status:string;promotion_mode:string;created_at:string}

export default function CampaignsPage(){
 const [rows,setRows]=useState<Campaign[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{fetch('/api/campaigns/list').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load campaigns');setRows(d.campaigns||[])}).catch(e=>setError(e instanceof Error?e.message:'Unable to load campaigns')).finally(()=>setLoading(false))},[])
 return <main className="min-h-screen bg-slate-50 px-5 py-10 dark:bg-slate-950"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-red-600">VSBILL Campaigns</p><h1 className="mt-2 text-4xl font-black">My campaigns</h1><p className="mt-2 text-slate-500">Track payment, policy review, delivery and completion from one place.</p></div><Link href="/campaigns/new" className="rounded-xl bg-red-600 px-5 py-3 font-bold text-white">Create campaign</Link></div>{error&&<p className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{loading?<div className="mt-8 glass rounded-2xl p-8 text-center">Loading campaigns…</div>:<div className="mt-8 space-y-4">{rows.map(c=><article key={c.id} className="glass rounded-2xl p-5"><div className="flex flex-wrap gap-4"><div className="h-20 w-32 overflow-hidden rounded-xl bg-slate-200">{c.thumbnail&&<img src={c.thumbnail} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-black">{c.youtube_video_title||'Untitled campaign'}</h2><p className="mt-1 text-sm text-slate-500">{c.promotion_mode} · {c.completed_count}/{c.quantity} completed</p><p className="mt-1 text-xs text-slate-400">Created {new Date(c.created_at).toLocaleString()}</p></div><div className="text-right"><Status label={c.status}/><p className="mt-2 font-bold">{c.currency} {(Number(c.total_charge_minor)/100).toFixed(2)}</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-red-600" style={{width:`${Math.min(100,Math.round((Number(c.completed_count)/Math.max(1,Number(c.quantity)))*100))}%`}}/></div><div className="mt-3 flex justify-between text-xs text-slate-500"><span>Policy: {c.policy_review_status}</span><span>{Math.min(100,Math.round((Number(c.completed_count)/Math.max(1,Number(c.quantity)))*100))}% delivered</span></div></article>)}{!rows.length&&<div className="glass rounded-2xl p-12 text-center"><h2 className="text-xl font-black">No campaigns yet</h2><p className="mt-2 text-slate-500">Create your first compliant campaign when your account is active.</p><Link href="/campaigns/new" className="mt-5 inline-block rounded-xl bg-red-600 px-5 py-3 font-bold text-white">Create campaign</Link></div>}</div>}</div></main>
}
function Status({label}:{label:string}){return <span className="rounded-full border px-3 py-1 text-xs font-bold capitalize">{label.replaceAll('_',' ')}</span>}
