import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { LayoutDashboard, PlaySquare, Megaphone, Wallet, Users, Settings, UserCircle } from 'lucide-react'

const nav=[['/dashboard','Dashboard',LayoutDashboard],['/dashboard/tasks','Watch Tasks',PlaySquare],['/campaigns','Campaigns',Megaphone],['/dashboard/earnings','Earnings',Wallet],['/dashboard/referrals','Referrals',Users],['/dashboard/profile','Profile',UserCircle],['/dashboard/settings','Settings',Settings]] as const

export default async function Dashboard(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/login');
 const {data:profile}=await supabase.from('users').select('name,email,balance,total_earned,is_paid,youtube_channel_title,strikes,is_banned,role').eq('id',user.id).single(); if(!profile)redirect('/register')
 return <main className="min-h-screen bg-slate-50 dark:bg-slate-950"><div className="mx-auto flex min-h-screen max-w-[1600px]"> <aside className="hidden w-64 border-r bg-white p-5 dark:bg-slate-900 md:block"><Link href="/" className="block px-3 py-4 text-lg font-black">VSBIL <span className="gradient-text">TUBE BOOST</span></Link><nav className="mt-5 space-y-1">{nav.map(([href,label,Icon])=><Link key={href} href={href} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-slate-800"><Icon className="h-4 w-4"/>{label}</Link>)}</nav></aside><section className="flex-1"><header className="flex items-center justify-between border-b bg-white px-6 py-4 dark:bg-slate-900"><div><p className="text-sm text-slate-500">Good to see you</p><h1 className="text-xl font-black">{profile.name||profile.email}</h1></div><div className="rounded-xl bg-slate-100 px-4 py-2 text-sm font-bold dark:bg-slate-800">Balance: GHS {Number(profile.balance).toFixed(2)}</div></header><div className="p-6 md:p-8"><div className="mb-8 rounded-2xl bg-gradient-to-br from-slate-950 to-blue-950 p-7 text-white"><div className="max-w-2xl"><p className="text-sm font-semibold text-red-300">Account status</p><h2 className="mt-2 text-3xl font-black">{profile.is_paid?'Your earning account is active.':'Complete activation to start earning.'}</h2><p className="mt-2 text-slate-300">{profile.is_paid?`Connected channel: ${profile.youtube_channel_title||'YouTube connection pending'}`:'Verify your email, connect YouTube and complete the $10 entry payment.'}</p>{!profile.is_paid&&<Link href="/pay-entry-fee" className="mt-5 inline-block rounded-xl bg-white px-5 py-3 font-bold text-slate-950">Activate account</Link>}</div></div><div className="grid gap-5 md:grid-cols-3"><Card title="Available balance" value={`GHS ${Number(profile.balance).toFixed(2)}`}/><Card title="Lifetime earned" value={`GHS ${Number(profile.total_earned).toFixed(2)}`}/><Card title="Trust strikes" value={`${profile.strikes}/3`}/></div><div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="glass rounded-2xl p-6"><h3 className="text-xl font-black">Quick actions</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/dashboard/tasks" className="rounded-xl border p-4 font-semibold">Find watch tasks →</Link><Link href="/campaigns/new" className="rounded-xl border p-4 font-semibold">Create a campaign →</Link></div></div><div className="glass rounded-2xl p-6"><h3 className="text-xl font-black">Safety score</h3><p className="mt-2 text-slate-500">Stay compliant: watch the required duration, keep subscriptions active, and never automate tasks.</p><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><div className="h-full w-4/5 rounded-full bg-blue-600"/></div></div></div></div></section></div></main>
}
function Card({title,value}:{title:string,value:string}){return <div className="glass rounded-2xl p-6"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
